### ISSUE TITLE
Nuxt3 Support? 🤓 

### ISSUE THREAD

**Issue by Clex1o1** [antfu/vue-starport#11]
I installed the package in my nuxt3 demo app and got this error:
```
[plugin:vite:import-analysis] Failed to resolve entry for package "vue-starport". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vue-starport". The package may have incorrect main/module/exports specified in its package.json.
```
Also VS Code show an error of missing types? 
```
Cannot find module 'vue-starport' or its corresponding type declarations.ts(2307)
```
Will there be nuxt3/SSR support? 

Anyway, thanks for your amazing work!

**Comment by tangdaoyuan** [comment]
> I installed the package in my nuxt3 demo app and got this error:
> 
> ```
> [plugin:vite:import-analysis] Failed to resolve entry for package "vue-starport". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vue-starport". The package may have incorrect main/module/exports specified in its package.json.
> ```
> 
> Also VS Code show an error of missing types?
> 
> ```
> Cannot find module 'vue-starport' or its corresponding type declarations.ts(2307)
> ```
> 
> Will there be nuxt3/SSR support?
> 
> Anyway, thanks for your amazing work!

It seems like a wrong build result  in v0.0.4. missing **dist** folder.

**Comment by antfu** [comment]
Should be fine with the latest version now.
