### ISSUE TITLE
What application do you use to create the graphs?

### ISSUE THREAD

**Issue by obtusedev** [antfu/vue-starport#35]
The [graphs](https://github.com/antfu/vue-starport/blob/main/graphs/graph2.png) look really nice. What do you use to create them?

**Comment by tangdaoyuan** [comment]
> graphs

maybe  you find  [this](https://www.tldraw.com/) ?   [Repo Here](https://github.com/tldraw/tldraw)

**Comment by obtusedev** [comment]
> > graphs
> 
> maybe you search [this](https://www.tldraw.com/) ? [Repo Here](https://github.com/tldraw/tldraw)

Thanks!
