### ISSUE TITLE
Cannot read properties of undefined (reading 'getInstance')

### ISSUE THREAD

**Issue by tangdaoyuan** [antfu/vue-starport#40]
In the latest version(v0.2.9),  It still doesn't work with vite-ssg, the error is as follow
<img width="739" alt="image" src="https://user-images.githubusercontent.com/8007202/165751148-ccb2f6ea-1358-4aea-a594-f5e537030f39.png">

the reason has already been mentioned [here](https://github.com/antfu/vue-starport/issues/36#issuecomment-1111715933): `injecting`  state before `providing` it

I try to provide a reproduction or test by using `router.isReady` in [this commit](https://github.com/antfu/vue-starport/pull/39/commits/08f5bfb16b9edcc5ba0a29d3092f7fa97d79ae2b) and try to fix by AsyncComponent

**Comment by Youdaman** [comment]
I'm getting the same issue.

This is when using the app.use way, i.e. `ctx.app.use(StarportPlugin({ keepAlive: true }))` in main.ts, and results in the components displaying as their component tags in the inspector Element tab rather then becoming the actual component.

If I try importing the modules directly as per the Usage instructions then the components do not render at all, the containing element is empty when you look in the inspector.

For example
```
<div>
    <!-- ... -->
    <Starport port="my-id" style="height:600px">
      <MyComponent :prop="value"/>
    </Starport>
  </div>
```
renders as `<starport port="my-id"...` etc with the app.use way, and with the per-page/App.vue imports it renders as just `<div></div>`

**Comment by antfu** [comment]
Updated the docs. Wrapping the router view with the carrier should solve the issue.

https://github.com/antfu/vue-starport#usage
