### ISSUE TITLE
不设置高度会出现warn警告，设置了高度动画会出现跳动

### ISSUE THREAD

**Issue by TTcom** [antfu/vue-starport#46]
![1652024293(1)](https://user-images.githubusercontent.com/29853303/167303757-724a792c-4b60-41a2-9362-92f35ee505e9.png)
复现项目：https://github.com/TTcom/starportTest
pnpm i 
pnpm dev

点击苹果图片会跳转路由，动画正常但是会有has no height警告

如果加上height 的话动画会有跳动的现象
![1652024508(1)](https://user-images.githubusercontent.com/29853303/167303892-db19a216-f107-4f9e-95c2-2773f61a5245.png)

**Comment by antfu** [comment]
It's not related to Starport. It's because of the transition you added for Route View. You can add https://github.com/antfu/vue-starport#debug to see what's going on. You might want to add "position: absolute" to your route views.

**Comment by bilibili-ayang** [comment]
> ![1652024293(1)](https://user-images.githubusercontent.com/29853303/167303757-724a792c-4b60-41a2-9362-92f35ee505e9.png) 修复项目：https://github.com/TTcom/starportTest pnpm i pnpm dev
> 
> 点击苹果图片会跳转路由，动画正常但会有没有高度警告
> 
> 如果加高的动图会有跳动的现像 ![1652024508(1)](https://user-images.githubusercontent.com/29853303/167303892-db19a216-f107-4f9e-95c2-2773f61a5245.png)

您好，我也遇到了同样的问题，请问您的最终的解决方案是什么，方便告知我学习一下吗？
