### ISSUE TITLE
Transitions not working in nuxt 3

### ISSUE THREAD

**Issue by davidmarkl** [antfu/vue-starport#49]
- Operating System: `Linux`/Windows
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.4-27588443.cf25525`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`

Reproduction:
https://stackblitz.com/edit/nuxt-starter-ekdzqf?file=tsconfig.json

Description:
On nuxt 3 everyting works except for the transitions. Probably this is due to nuxt wrapping the app in suspense.

**Comment by Redemption198** [comment]
Still not working in RC11

**Comment by yuji1548** [comment]
Transitions can working in RC13 now. Surprise

**Comment by k16e-me** [comment]
Wait, it's Jan 2023, N3 is stable, this issue is closed, but I'm seeing that <Transition> is not working in Nuxt 3. Now, I don't mean page transition, but simple Vue 3 transitions of elements, etc. I'm trying so hard and seeing nothing, just silent
