### ISSUE TITLE
vue-starport and vue's keepAlive are mutually exclusive

### ISSUE THREAD

**Issue by ayangweb** [antfu/vue-starport#54]
### Describe the bug

Hello, I have a conflict between vue-starport and vue's KeepAlive. I cannot use keepalive when I can use vue-starport, and vice versa.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/75017711/204997750-0b18c332-364f-4791-9f6f-f6fc53378fdf.png">

### Reproduction

 <RouterView v-slot="{ Component }">     <KeepAlive>       <StarportCarrier>         <component :is="Component" />       </StarportCarrier>     </KeepAlive>   </RouterView>

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 116.19 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Safari: 16.0
```

### Used Package Manager

yarn

### Validations

- [x] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by haiya6** [comment]
You should make `<StarportCarrier />` the parent of `<RouterView />`.

**Comment by bilibili-ayang** [comment]
> You should make `<StarportCarrier />` the parent of `<RouterView />`.

Thank you for your answer, but after wrapping the StarportCarrier to the outside, the following error will be reported: [Vue Starport] Multiple proxies of "index" with port "xxx" detected.

<img width="389" alt="image" src="https://user-images.githubusercontent.com/75017711/205427913-7415c69d-b324-42c5-bcf9-488860ee79c2.png">


<img width="696" alt="image" src="https://user-images.githubusercontent.com/75017711/205427899-d0b29b32-156a-4567-b944-62c4cb41f81c.png">

**Comment by bilibili-ayang** [comment]
> You should make `<StarportCarrier />` the parent of `<RouterView />`.

Thank you for your answer, but after wrapping the StarportCarrier to the very outside, the following error is reported: [Vue Starport] Multiple proxies of "index" with port "xxx" detected. The later one will be ignored.

<img width="322" alt="image" src="https://user-images.githubusercontent.com/75017711/205427959-fb25068a-7a78-447a-b98c-0fbef76c32ca.png">

<img width="589" alt="image" src="https://user-images.githubusercontent.com/75017711/205427964-8996d1c2-3277-45d8-a76d-046d6faae354.png">

**Comment by bilibili-ayang** [comment]
> You should make `<StarportCarrier />` the parent of `<RouterView />`.

Thank you for your answer, but after wrapping the StarportCarrier to the outside, the following error is reported：[Vue Starport] Multiple proxies of "index" with port "xxx" detected. The later one will be ignored.

<img width="333" alt="image" src="https://user-images.githubusercontent.com/75017711/205427991-1f737ccb-83a6-44f9-af35-8e9b1de0263d.png">

<img width="585" alt="image" src="https://user-images.githubusercontent.com/75017711/205427996-3679db5d-e50e-479c-a933-465f8692e3fe.png">

**Comment by haiya6** [comment]
Looks like working with KeepAlive is not supported yet.
